//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SqlGenerator.Model;

namespace SqlGenerator.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"(localdb)\MQSSQLLocalDB")]
        public string Server
        {
            get
            {
                return ((string)(this["Server"]));
            }
            set
            {
                this["Server"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-- Example script:\r\n\r\nSELECT * FROM Nutshell.dbo.Customers")]
        public string LastScriptRan
        {
            get
            {
                return ((string)(this["LastScriptRan"]));
            }
            set
            {
                this["LastScriptRan"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSqlOutput
        {
            get
            {
                return ((string)(this["LastSqlOutput"]));
            }
            set
            {
                this["LastSqlOutput"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastCSharpOutput
        {
            get
            {
                return ((string)(this["LastCSharpOutput"]));
            }
            set
            {
                this["LastCSharpOutput"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(null)]
        public ScriptResultList ScriptResultList
        {
            get
            {
                return ((ScriptResultList)(this["ScriptResultList"]));
            }
            set
            {
                this["ScriptResultList"] = value;
            }
        }
    }
}
